export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  AUTH_UNAUTHORIZED_EMAIL = 'AUTH_UNAUTHORIZED_EMAIL',
  AUTH_INVALID_OTP_REQUEST = 'AUTH_INVALID_OTP_REQUEST',
  AUTH_OTP_EXPIRED = 'AUTH_OTP_EXPIRED',
  AUTH_INVALID_OTP = 'AUTH_INVALID_OTP',
  AUTH_GOOGLE_NO_USER = 'AUTH_GOOGLE_NO_USER',
  AUTH_GOOGLE_PROFILE_INVALID = 'AUTH_GOOGLE_PROFILE_INVALID',

  EMAIL_DELIVERY_FAILED = 'EMAIL_DELIVERY_FAILED',

  PROFILE_SOCIAL_LINK_NOT_FOUND = 'PROFILE_SOCIAL_LINK_NOT_FOUND',
  PROFILE_SKILL_CATEGORY_NOT_FOUND = 'PROFILE_SKILL_CATEGORY_NOT_FOUND',
  PROFILE_SKILL_NOT_FOUND = 'PROFILE_SKILL_NOT_FOUND',

  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_SLUG_CONFLICT = 'PROJECT_SLUG_CONFLICT',

  SKILL_NOT_FOUND = 'SKILL_NOT_FOUND',
  SKILL_NAME_CONFLICT = 'SKILL_NAME_CONFLICT',

  CV_NOT_FOUND = 'CV_NOT_FOUND',

  UPLOAD_UNSUPPORTED_FILE_TYPE = 'UPLOAD_UNSUPPORTED_FILE_TYPE',
  UPLOAD_FILE_TOO_LARGE = 'UPLOAD_FILE_TOO_LARGE',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
}
